# $OpenBSD: Makefile,v 1.19 2019/07/12 20:47:49 sthen Exp $

COMMENT=		graph construction, manipulation and processing framework

V=              0.1.1f
PKGNAME=        ade

GH_ACCOUNT=     opencv
GH_PROJECT=     ade
GH_TAGNAME=     v${V}

CATEGORIES=		misc

HOMEPAGE=		https://github.com/opencv/ade

# MIT/X
PERMIT_PACKAGE=	Yes

WANTLIB += c

NO_TEST=     		Yes

MODULES=        devel/cmake

.include <bsd.port.mk>
